baseURL = "https://limaochang.dev/"
languageCode = "en"
defaultContentLanguage = "en"

theme = "congo"

enableRobotsTXT = true
paginate = 10
summaryLength = 0

[outputs]
  home = ["HTML", "RSS", "JSON"]
