languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Limao Chang"
copyright = "© 2024 Limao Chang"

[params]
  dateFormat = "2 January 2006"

  mainSections = ["resume", "projects"]
  description = "Limao Chang's personal website"

[params.author]
  name = "Limao Chang"
  image = "img/me.jpg"
  headline = "Maths Honours @ UQ, Maths/Stats & CS grad @ UQ"
  bio = "Maths Honours @ UQ, Maths/Stats & CS grad @ UQ"
  links = [
    { github = "https://github.com/LimaoC" },
    { linkedin = "https://linkedin.com/in/limao-chang" },
  ]
