languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Limao Chang"
copyright = "Copy, _right?_ :thinking_face:"

[params]
  dateFormat = "2 January 2006"

  # mainSections = ["section1", "section2"]
  # description = "My awesome website"

[params.author]
  name = "Limao Chang"
  image = "img/me.jpg"
  headline = "Fourth Year Mathematics (Statistics) & Computer Science @ UQ"
  bio = "Fourth Year Mathematics (Statistics) & Computer Science @ UQ"
  links = [
    { github = "https://github.com/LimaoC" },
    { linkedin = "https://linkedin.com/in/limao-chang" },
  ]
